/**********************************************************************/
/*                                                                    */
/*  exdcl.h extra functions declaration file.                         */
/*                                                                    */
/**********************************************************************/
/*                                                                    */
/* This is ZEDIT source material.                                     */
/*                                                                    */
/* ZEDIT Source Materials are intellectual property                   */
/*     (c) Copyright 1987,2001 by Clyde Thomas Zuber.                 */
/*                                                                    */
/**********************************************************************/
extern char  *itoa(int val, char *str, int bse);
