/**********************************************************************/
/* ZEDITALL.CMD - compile all OS versions                             */
/**********************************************************************/
'@echo off'
'@call zeditcmp 3'
'@call zeditcmp 3p'
'@call zeditcmp 3t'
'@call zeditcmp 3m'
'@call zeditcmp 3mt'
'@call zeditcmp 3w'
'@call zeditcmp 2'
'@call zeditcmp 2t'
'@call zeditcmp 1'
'@call incsetp'
